//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.01 at 10:04:03 PM CEST 
//


package org.opentelecoms.gsm0348.api.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CipheringAlgorithmMode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CipheringAlgorithmMode"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="DES_CBC"/&gt;
 *     &lt;enumeration value="TRIPLE_DES_CBC_2_KEYS"/&gt;
 *     &lt;enumeration value="TRIPLE_DES_CBC_3_KEYS"/&gt;
 *     &lt;enumeration value="DES_ECB"/&gt;
 *     &lt;enumeration value="AES_CBC"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CipheringAlgorithmMode")
@XmlEnum
public enum CipheringAlgorithmMode {

    DES_CBC,
    TRIPLE_DES_CBC_2_KEYS,
    TRIPLE_DES_CBC_3_KEYS,
    DES_ECB,
    AES_CBC;

    public String value() {
        return name();
    }

    public static CipheringAlgorithmMode fromValue(String v) {
        return valueOf(v);
    }

}
