//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.01 at 10:04:03 PM CEST 
//


package org.opentelecoms.gsm0348.api.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.opentelecoms.gsm0348.api.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.opentelecoms.gsm0348.api.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PacketHeader }
     * 
     */
    public PacketHeader createPacketHeader() {
        return new PacketHeader();
    }

    /**
     * Create an instance of {@link Packet }
     * 
     */
    public Packet createPacket() {
        return new Packet();
    }

    /**
     * Create an instance of {@link CommandPacketHeader }
     * 
     */
    public CommandPacketHeader createCommandPacketHeader() {
        return new CommandPacketHeader();
    }

    /**
     * Create an instance of {@link SecurityHeader }
     * 
     */
    public SecurityHeader createSecurityHeader() {
        return new SecurityHeader();
    }

    /**
     * Create an instance of {@link ResponsePacketHeader }
     * 
     */
    public ResponsePacketHeader createResponsePacketHeader() {
        return new ResponsePacketHeader();
    }

    /**
     * Create an instance of {@link CommandPacket }
     * 
     */
    public CommandPacket createCommandPacket() {
        return new CommandPacket();
    }

    /**
     * Create an instance of {@link ResponsePacket }
     * 
     */
    public ResponsePacket createResponsePacket() {
        return new ResponsePacket();
    }

    /**
     * Create an instance of {@link KIC }
     * 
     */
    public KIC createKIC() {
        return new KIC();
    }

    /**
     * Create an instance of {@link KID }
     * 
     */
    public KID createKID() {
        return new KID();
    }

    /**
     * Create an instance of {@link CommandSPI }
     * 
     */
    public CommandSPI createCommandSPI() {
        return new CommandSPI();
    }

    /**
     * Create an instance of {@link ResponseSPI }
     * 
     */
    public ResponseSPI createResponseSPI() {
        return new ResponseSPI();
    }

    /**
     * Create an instance of {@link SPI }
     * 
     */
    public SPI createSPI() {
        return new SPI();
    }

    /**
     * Create an instance of {@link CardProfile }
     * 
     */
    public CardProfile createCardProfile() {
        return new CardProfile();
    }

}
