//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.01 at 10:04:03 PM CEST 
//


package org.opentelecoms.gsm0348.api.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PoRMode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PoRMode"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="NO_REPLY"/&gt;
 *     &lt;enumeration value="REPLY_ALWAYS"/&gt;
 *     &lt;enumeration value="REPLY_WHEN_ERROR"/&gt;
 *     &lt;enumeration value="RESERVED"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PoRMode")
@XmlEnum
public enum PoRMode {

    NO_REPLY,
    REPLY_ALWAYS,
    REPLY_WHEN_ERROR,
    RESERVED;

    public String value() {
        return name();
    }

    public static PoRMode fromValue(String v) {
        return valueOf(v);
    }

}
