//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.01 at 10:04:03 PM CEST 
//


package org.opentelecoms.gsm0348.api.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResponsePacketStatus.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ResponsePacketStatus"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="POR_OK"/&gt;
 *     &lt;enumeration value="RC_CC_DS_FAILED"/&gt;
 *     &lt;enumeration value="CNTR_LOW"/&gt;
 *     &lt;enumeration value="CNTR_HIGH"/&gt;
 *     &lt;enumeration value="CNTR_BLOCKED"/&gt;
 *     &lt;enumeration value="CIPHERING_ERROR"/&gt;
 *     &lt;enumeration value="UNIDENTIFIED_SECURITY_ERROR"/&gt;
 *     &lt;enumeration value="INSUFFICIENT_MEMORY"/&gt;
 *     &lt;enumeration value="MORE_TIME"/&gt;
 *     &lt;enumeration value="TAR_UNKNOWN"/&gt;
 *     &lt;enumeration value="INSUFFICIENT_SECURITY_LEVEL"/&gt;
 *     &lt;enumeration value="TO_BE_SENT_VIA_SMS_SUBMIT"/&gt;
 *     &lt;enumeration value="TO_BE_SENT_VIA_PROCESSUNSTRUCTUREDSS_REQUEST"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ResponsePacketStatus")
@XmlEnum
public enum ResponsePacketStatus {

    POR_OK,
    RC_CC_DS_FAILED,
    CNTR_LOW,
    CNTR_HIGH,
    CNTR_BLOCKED,
    CIPHERING_ERROR,
    UNIDENTIFIED_SECURITY_ERROR,
    INSUFFICIENT_MEMORY,
    MORE_TIME,
    TAR_UNKNOWN,
    INSUFFICIENT_SECURITY_LEVEL,
    TO_BE_SENT_VIA_SMS_SUBMIT,
    TO_BE_SENT_VIA_PROCESSUNSTRUCTUREDSS_REQUEST;

    public String value() {
        return name();
    }

    public static ResponsePacketStatus fromValue(String v) {
        return valueOf(v);
    }

}
