//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.01 at 10:04:03 PM CEST 
//


package org.opentelecoms.gsm0348.api.model;

import java.util.Objects;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import org.opentelecoms.gsm0348.api.Util;


/**
 * <p>Java class for ResponsePacketHeader complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResponsePacketHeader"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{org.opentelecoms.gsm0348}SecurityHeader"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ResponseStatus" type="{org.opentelecoms.gsm0348}ResponsePacketStatus"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResponsePacketHeader", propOrder = {
    "responseStatus"
})
public class ResponsePacketHeader
    extends SecurityHeader
{

    @XmlElement(name = "ResponseStatus", required = true)
    @XmlSchemaType(name = "string")
    protected ResponsePacketStatus responseStatus;

    /**
     * Gets the value of the responseStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ResponsePacketStatus }
     *     
     */
    public ResponsePacketStatus getResponseStatus() {
        return responseStatus;
    }

    /**
     * Sets the value of the responseStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponsePacketStatus }
     *     
     */
    public void setResponseStatus(ResponsePacketStatus value) {
        this.responseStatus = value;
    }

    @Override
    public boolean equals(final Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof ResponsePacketHeader)) {
            return false;
        }
        final ResponsePacketHeader that = (ResponsePacketHeader) o;
        return responseStatus == that.responseStatus;
    }

    @Override
    public int hashCode() {
        return Objects.hash(responseStatus);
    }

    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("ResponsePacketHeader [responseStatus=");
        builder.append(responseStatus);
        builder.append(", tar=");
        builder.append(Util.toHexString(tar));
        builder.append(", paddingCounter=");
        builder.append(Util.toHex(paddingCounter));
        builder.append(", checksumSignature=");
        builder.append(Util.toHexString(security));
        builder.append(", counter=");
        builder.append(Util.toHexString(counter));
        builder.append("]");
        return builder.toString();
    }

}
