//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.01 at 10:04:03 PM CEST 
//


package org.opentelecoms.gsm0348.api.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SynchroCounterMode.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SynchroCounterMode"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="NO_COUNTER"/&gt;
 *     &lt;enumeration value="COUNTER_NO_REPLAY_NO_CHECK"/&gt;
 *     &lt;enumeration value="COUNTER_REPLAY_OR_CHECK"/&gt;
 *     &lt;enumeration value="COUNTER_REPLAY_OR_CHECK_INCREMENT"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "SynchroCounterMode")
@XmlEnum
public enum SynchroCounterMode {

    NO_COUNTER,
    COUNTER_NO_REPLAY_NO_CHECK,
    COUNTER_REPLAY_OR_CHECK,
    COUNTER_REPLAY_OR_CHECK_INCREMENT;

    public String value() {
        return name();
    }

    public static SynchroCounterMode fromValue(String v) {
        return valueOf(v);
    }

}
